#!/usr/bin/env python3

# TODO
import os
import sys
import helpers

from analyzer import Analyzer
from termcolor import colored

def main():

    # ensure proper usage
    if len(sys.argv) != 2:
        sys.exit("Usage: ./tweet @screen_name")

    screen_name = sys.argv[1]


    # get screen_name's tweets
    tweets = helpers.get_user_timeline(screen_name, 50)

    # absolute paths to lists
    positives = os.path.join(sys.path[0], "positive-words.txt")
    negatives = os.path.join(sys.path[0], "negative-words.txt")

    # instantiate analyzer
    analyzer = Analyzer(positives, negatives)


    # analyze word
    for i in range(len(tweets)):
        score = analyzer.analyze(tweets[i])
        if score > 0.0:
            print(colored(f"1 {tweets[i]}", "green"))
        elif score < 0.0:
            print(colored(f"-1 {tweets[i]}", "red"))
        else:
            print(colored(f"0 {tweets[i]}", "yellow"))

    #print(f"{tweets}")




if __name__ == "__main__":
    main()
